export const COLOR_MAP: Record<string, string> = {
    black: '#000000',
    white: '#FFFFFF',
    red: '#EF4444',
    blue: '#3B82F6',
    green: '#22C55E',
    yellow: '#EAB308',
    pink: '#EC4899',
    purple: '#A855F7',
    orange: '#F97316',
    gray: '#6B7280',
    brown: '#92400E',
    navy: '#1E3A5F',
    maroon: '#800000',
    olive: '#808000',
    mustard: '#FFDB58',
    magenta: '#FF00FF',
    lavender: '#E6E6FA',
    beige: '#F5F5DC',
    silver: '#C0C0C0',
    gold: '#FFD700',
    multi: 'linear-gradient(to right, red, orange, yellow, green, blue, indigo, violet)',
    multicolor: 'linear-gradient(to right, red, orange, yellow, green, blue, indigo, violet)',
    cream: '#FFFDD0',
    'light blue': '#ADD8E6',
    'dark blue': '#00008B',
    'navy blue': '#000080',
    'royal blue': '#4169E1',
    'sky blue': '#87CEEB',
    'midnight blue': '#191970',
    bronze: '#CD7F32',
    burgundy: '#800020',
    charcoal: '#36454F',
    indigo: '#4B0082',
    violet: '#EE82EE',
    cyan: '#00FFFF',
    turquoise: '#40E0D0',
    mint: '#98FF98',
    teal: '#14B8A6',
    coral: '#FF7F50',
}

export const COLORS = [
    { value: 'black', label: 'Black', hex: COLOR_MAP.black },
    { value: 'white', label: 'White', hex: COLOR_MAP.white },
    { value: 'red', label: 'Red', hex: COLOR_MAP.red },
    { value: 'blue', label: 'Blue', hex: COLOR_MAP.blue },
    { value: 'green', label: 'Green', hex: COLOR_MAP.green },
    { value: 'yellow', label: 'Yellow', hex: COLOR_MAP.yellow },
    { value: 'pink', label: 'Pink', hex: COLOR_MAP.pink },
    { value: 'purple', label: 'Purple', hex: COLOR_MAP.purple },
    { value: 'orange', label: 'Orange', hex: COLOR_MAP.orange },
    { value: 'gray', label: 'Gray', hex: COLOR_MAP.gray },
    { value: 'brown', label: 'Brown', hex: COLOR_MAP.brown },
    { value: 'navy', label: 'Navy', hex: COLOR_MAP.navy },
    { value: 'maroon', label: 'Maroon', hex: COLOR_MAP.maroon },
    { value: 'olive', label: 'Olive', hex: COLOR_MAP.olive },
    { value: 'mustard', label: 'Mustard', hex: COLOR_MAP.mustard },
    { value: 'magenta', label: 'Magenta', hex: COLOR_MAP.magenta },
    { value: 'lavender', label: 'Lavender', hex: COLOR_MAP.lavender },
    { value: 'beige', label: 'Beige', hex: COLOR_MAP.beige },
    { value: 'silver', label: 'Silver', hex: COLOR_MAP.silver },
    { value: 'gold', label: 'Gold', hex: COLOR_MAP.gold },
    { value: 'multi', label: 'Multicolor', hex: COLOR_MAP.multi },
]
