-- Phase 5: Dropping Obsolete RLS Policies
DROP POLICY IF EXISTS "Admin write access" ON cms_menus;
DROP POLICY IF EXISTS "Chairman and Admin full access to main categories" ON main_categories;
DROP POLICY IF EXISTS "Chairman and Admin full access to sub categories" ON sub_categories;
DROP POLICY IF EXISTS "Admins can view all orders" ON orders;
DROP POLICY IF EXISTS "Admins can update all orders" ON orders;
DROP POLICY IF EXISTS "Admins can manage campaigns" ON marketing_campaigns;
DROP POLICY IF EXISTS "Admins can manage app settings" ON app_settings;
DROP POLICY IF EXISTS "Admins can view inventory logs" ON inventory_logs;
DROP POLICY IF EXISTS "Admins can insert inventory logs" ON inventory_logs;
DROP POLICY IF EXISTS "Admins can view audit logs" ON audit_logs;
DROP POLICY IF EXISTS "products_admin_write" ON products;
DROP POLICY IF EXISTS "inventory_admin_write" ON product_inventory;
DROP POLICY IF EXISTS "Enable read/write for own settings" ON seller_settings;
DROP POLICY IF EXISTS "Enable update for admins only" ON store_settings;
DROP POLICY IF EXISTS "Enable insert for admins only" ON store_settings;
DROP POLICY IF EXISTS "Admin/Seller manage media" ON product_media;
DROP POLICY IF EXISTS "Admins can manage all stores" ON stores;
DROP POLICY IF EXISTS "Admins can manage all products" ON products;
DROP POLICY IF EXISTS "Admins can manage all inventory" ON product_inventory;
DROP POLICY IF EXISTS "Admins can manage all orders" ON orders;
DROP POLICY IF EXISTS "Admins can view seller settings" ON seller_settings;
DROP POLICY IF EXISTS "Admins can update seller settings" ON seller_settings;
DROP POLICY IF EXISTS "Admins can insert seller settings" ON seller_settings;
DROP POLICY IF EXISTS "Admins can all reservations" ON inventory_reservations;
DROP POLICY IF EXISTS "Admins can manage store settings" ON store_settings;
DROP POLICY IF EXISTS "Admins can view logs" ON audit_logs;
DROP POLICY IF EXISTS "Admins can view all fees" ON platform_fees;
DROP POLICY IF EXISTS "Admins can manage all coupons" ON coupons;
DROP POLICY IF EXISTS "Admins can manage collections" ON collections;
DROP POLICY IF EXISTS "Admins can manage product_categories" ON product_categories;
DROP POLICY IF EXISTS "Admins can manage content_blocks" ON content_blocks;
DROP POLICY IF EXISTS "Admins can read quick actions" ON quick_actions;
DROP POLICY IF EXISTS "Allow admins to view" ON analytics_events;
DROP POLICY IF EXISTS "Admins can view page views" ON page_views;
DROP POLICY IF EXISTS "Admins view all generations" ON generations;
DROP POLICY IF EXISTS "Admins manage categories" ON categories;
DROP POLICY IF EXISTS "Admins view search logs" ON search_logs;
DROP POLICY IF EXISTS "Admins view all wishlists" ON wishlists;
DROP POLICY IF EXISTS "Admins manage media" ON product_media;
DROP POLICY IF EXISTS "Admins view all" ON analytics_events;

-- Phase 5: Dropping Obsolete Tables
DROP TABLE IF EXISTS seller_settings CASCADE;
DROP TABLE IF EXISTS seller_team_members CASCADE;
DROP TABLE IF EXISTS seller_profiles CASCADE;
DROP TABLE IF EXISTS ad_campaigns CASCADE;
DROP TABLE IF EXISTS ad_stats_daily CASCADE;
DROP TABLE IF EXISTS ad_spend CASCADE;
DROP TABLE IF EXISTS ad_conversions CASCADE;
DROP TABLE IF EXISTS ad_clicks CASCADE;
DROP TABLE IF EXISTS ad_placements CASCADE;
DROP TABLE IF EXISTS ad_impressions CASCADE;
DROP TABLE IF EXISTS ads CASCADE;
DROP TABLE IF EXISTS admin_login_log CASCADE;
